// Code generated by go-bindata.
// sources:
// assets/css/bootstrap.min.css
// assets/css/material-dashboard.css
// assets/img/favicon.ico
// assets/img/sidebar.jpg
// assets/js/bootstrap-notify.js
// assets/js/bootstrap.min.js
// assets/js/chartist.min.js
// assets/js/jquery-3.1.0.min.js
// assets/js/material-dashboard.js
// assets/js/material.min.js
// assets/templates/base.html
// DO NOT EDIT!

package assets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// cssBootstrapMinCss reads file data from disk. It returns an error on failure.
func cssBootstrapMinCss() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/css/bootstrap.min.css"
	name := "css/bootstrap.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// cssMaterialDashboardCss reads file data from disk. It returns an error on failure.
func cssMaterialDashboardCss() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/css/material-dashboard.css"
	name := "css/material-dashboard.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// imgFaviconIco reads file data from disk. It returns an error on failure.
func imgFaviconIco() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/img/favicon.ico"
	name := "img/favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// imgSidebarJpg reads file data from disk. It returns an error on failure.
func imgSidebarJpg() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/img/sidebar.jpg"
	name := "img/sidebar.jpg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsBootstrapNotifyJs reads file data from disk. It returns an error on failure.
func jsBootstrapNotifyJs() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/js/bootstrap-notify.js"
	name := "js/bootstrap-notify.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsBootstrapMinJs reads file data from disk. It returns an error on failure.
func jsBootstrapMinJs() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/js/bootstrap.min.js"
	name := "js/bootstrap.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsChartistMinJs reads file data from disk. It returns an error on failure.
func jsChartistMinJs() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/js/chartist.min.js"
	name := "js/chartist.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsJquery310MinJs reads file data from disk. It returns an error on failure.
func jsJquery310MinJs() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/js/jquery-3.1.0.min.js"
	name := "js/jquery-3.1.0.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsMaterialDashboardJs reads file data from disk. It returns an error on failure.
func jsMaterialDashboardJs() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/js/material-dashboard.js"
	name := "js/material-dashboard.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsMaterialMinJs reads file data from disk. It returns an error on failure.
func jsMaterialMinJs() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/js/material.min.js"
	name := "js/material.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesBaseHtml reads file data from disk. It returns an error on failure.
func templatesBaseHtml() (*asset, error) {
	path := "/Users/Jay/go/src/github.com/socialplanner/instahelper/assets/templates/base.html"
	name := "templates/base.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"css/bootstrap.min.css": cssBootstrapMinCss,
	"css/material-dashboard.css": cssMaterialDashboardCss,
	"img/favicon.ico": imgFaviconIco,
	"img/sidebar.jpg": imgSidebarJpg,
	"js/bootstrap-notify.js": jsBootstrapNotifyJs,
	"js/bootstrap.min.js": jsBootstrapMinJs,
	"js/chartist.min.js": jsChartistMinJs,
	"js/jquery-3.1.0.min.js": jsJquery310MinJs,
	"js/material-dashboard.js": jsMaterialDashboardJs,
	"js/material.min.js": jsMaterialMinJs,
	"templates/base.html": templatesBaseHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"css": &bintree{nil, map[string]*bintree{
		"bootstrap.min.css": &bintree{cssBootstrapMinCss, map[string]*bintree{}},
		"material-dashboard.css": &bintree{cssMaterialDashboardCss, map[string]*bintree{}},
	}},
	"img": &bintree{nil, map[string]*bintree{
		"favicon.ico": &bintree{imgFaviconIco, map[string]*bintree{}},
		"sidebar.jpg": &bintree{imgSidebarJpg, map[string]*bintree{}},
	}},
	"js": &bintree{nil, map[string]*bintree{
		"bootstrap-notify.js": &bintree{jsBootstrapNotifyJs, map[string]*bintree{}},
		"bootstrap.min.js": &bintree{jsBootstrapMinJs, map[string]*bintree{}},
		"chartist.min.js": &bintree{jsChartistMinJs, map[string]*bintree{}},
		"jquery-3.1.0.min.js": &bintree{jsJquery310MinJs, map[string]*bintree{}},
		"material-dashboard.js": &bintree{jsMaterialDashboardJs, map[string]*bintree{}},
		"material.min.js": &bintree{jsMaterialMinJs, map[string]*bintree{}},
	}},
	"templates": &bintree{nil, map[string]*bintree{
		"base.html": &bintree{templatesBaseHtml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

